version: '3.7'
services:
  bc-mysql:
    image: mysql:8.0
    container_name: bc-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    network_mode: host
    volumes:
      - ./database:/var/lib/mysql
      - ./var_run_mysqld:/var/run/mysqld
      # TODO share /var/run/mysqld/mysqld.sock between containers
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3306:3306/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ADMIN_PASSWORD
      TZ: $TZ

  bluecherry:
    image: bluecherrydvr/bluecherry:latest
    container_name: bc-server
    cap_add:
      - NET_BIND_SERVICE
    build:
      context: ./server/
      args:
        MYSQL_ADMIN_PASSWORD: $MYSQL_ADMIN_PASSWORD
        # MYSQL_ADMIN_LOGIN: $MYSQL_ADMIN_LOGIN
        # BLUECHERRY_DB_USER: $BLUECHERRY_DB_USER
        BLUECHERRY_DB_PASSWORD: $BLUECHERRY_DB_PASSWORD
        # BLUECHERRY_DB_NAME: $BLUECHERRY_DB_NAME
        # BLUECHERRY_DB_HOST: $BLUECHERRY_DB_HOST
        # BLUECHERRY_DB_ACCESS_HOST: $BLUECHERRY_DB_ACCESS_HOST
        # BLUECHERRY_LINUX_GROUP_ID: $BLUECHERRY_LINUX_GROUP_ID
        # BLUECHERRY_LINUX_USER_ID: $BLUECHERRY_LINUX_USER_ID
    restart: unless-stopped
    network_mode: host # for ONVIF discovery
    volumes:
      - ./recordings:/var/lib/bluecherry/recordings
      - ./data/bconf:/var/lib/bluecherry/.local/share/data/bconf
      - ./data/letsencrypt:/usr/share/bluecherry/nginx-includes/letsencrypt
      - ./data/backups:/usr/share/bluecherry/backups
      - ./var_run_mysqld:/var/run/mysqld
      # - ./server/bluecherry.conf:/etc/bluecherry.conf
    # Enable this only if you have a supported VAAPI device and /dev/dri exists on the host system.
    # devices:
    #   - /dev/dri:/dev/dri
    ports:
      - "7001:7001/tcp"
      - "7002:7002/tcp"
    env_file:
      - ./.env
    depends_on:
      - bc-mysql
